repos:
  - repo: local
    hooks:
      - id: isort --profile black .
        name: Sorting import statements
        entry: bash -c 'isort "$@"; git add -u' --
        language: python
        args: ["--profile", "black", "--filter-files"]
        files: \.py$
      - id: black .
        name: Black Python code formatting
        entry: bash -c 'black "$@"; git add -u' --
        language: python
        types: [python]
        args: ["--line-length=120"]
      - id: mypy
        name: Optional static type checker
        entry: bash -c 'mypy "$@"; git add -u' --
        language: python
        files: \.py$
